### ISSUE TITLE
TypeError: no implicit conversion of String into Array

### ISSUE THREAD

**Issue by yegor256** [yegor256/cobench#30]
```
TypeError: no implicit conversion of String into Array
   	/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/cobench-0.0.31/lib/cobench/metrics/pulls.rb:46:in `+'
   	/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/cobench-0.0.31/lib/cobench/metrics/pulls.rb:46:in `block in take'
   	/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/cobench-0.0.31/lib/cobench/metrics/pulls.rb:42:in `count'
   	/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/cobench-0.0.31/lib/cobench/metrics/pulls.rb:42:in `take'
   	/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/cobench-0.0.31/bin/cobench:124:in `block (2 levels) in build_xml'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.32`
